services:
  backend:
    container_name: assessment-backend
    build:
      context: ./assessment-backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./assessment-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://assessment-backend:8080
    depends_on:
      - backend